/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',  // <-- Added this line
        primary: {
          50: 'rgb(var(--color-primary), 0.05)',
          100: 'rgb(var(--color-primary), 0.1)',
          200: 'rgb(var(--color-primary), 0.2)',
          300: 'rgb(var(--color-primary), 0.3)',
          400: 'rgb(var(--color-primary), 0.4)',
          500: 'rgb(var(--color-primary), 0.7)',
          600: 'rgb(var(--color-primary), 0.8)',
          700: 'rgb(var(--color-primary), 0.9)',
          800: 'rgb(var(--color-primary), 0.95)',
          900: 'rgb(var(--color-primary), 1)',
        },
        secondary: {
          50: 'rgb(var(--color-secondary), 0.05)',
          100: 'rgb(var(--color-secondary), 0.1)',
          200: 'rgb(var(--color-secondary), 0.2)',
          300: 'rgb(var(--color-secondary), 0.3)',
          400: 'rgb(var(--color-secondary), 0.4)',
          500: 'rgb(var(--color-secondary), 0.7)',
          600: 'rgb(var(--color-secondary), 0.8)',
          700: 'rgb(var(--color-secondary), 0.9)',
          800: 'rgb(var(--color-secondary), 0.95)',
          900: 'rgb(var(--color-secondary), 1)',
        },
        accent: {
          50: 'rgb(var(--color-accent), 0.05)',
          100: 'rgb(var(--color-accent), 0.1)',
          200: 'rgb(var(--color-accent), 0.2)',
          300: 'rgb(var(--color-accent), 0.3)',
          400: 'rgb(var(--color-accent), 0.4)',
          500: 'rgb(var(--color-accent), 0.7)',
          600: 'rgb(var(--color-accent), 0.8)',
          700: 'rgb(var(--color-accent), 0.9)',
          800: 'rgb(var(--color-accent), 0.95)',
          900: 'rgb(var(--color-accent), 1)',
        },
        success: {
          50: 'rgb(var(--color-success), 0.05)',
          100: 'rgb(var(--color-success), 0.1)',
          200: 'rgb(var(--color-success), 0.2)',
          300: 'rgb(var(--color-success), 0.3)',
          400: 'rgb(var(--color-success), 0.4)',
          500: 'rgb(var(--color-success), 0.7)',
          600: 'rgb(var(--color-success), 0.8)',
          700: 'rgb(var(--color-success), 0.9)',
          800: 'rgb(var(--color-success), 0.95)',
          900: 'rgb(var(--color-success), 1)',
        },
        warning: {
          50: 'rgb(var(--color-warning), 0.05)',
          100: 'rgb(var(--color-warning), 0.1)',
          200: 'rgb(var(--color-warning), 0.2)',
          300: 'rgb(var(--color-warning), 0.3)',
          400: 'rgb(var(--color-warning), 0.4)',
          500: 'rgb(var(--color-warning), 0.7)',
          600: 'rgb(var(--color-warning), 0.8)',
          700: 'rgb(var(--color-warning), 0.9)',
          800: 'rgb(var(--color-warning), 0.95)',
          900: 'rgb(var(--color-warning), 1)',
        },
        error: {
          50: 'rgb(var(--color-error), 0.05)',
          100: 'rgb(var(--color-error), 0.1)',
          200: 'rgb(var(--color-error), 0.2)',
          300: 'rgb(var(--color-error), 0.3)',
          400: 'rgb(var(--color-error), 0.4)',
          500: 'rgb(var(--color-error), 0.7)',
          600: 'rgb(var(--color-error), 0.8)',
          700: 'rgb(var(--color-error), 0.9)',
          800: 'rgb(var(--color-error), 0.95)',
          900: 'rgb(var(--color-error), 1)',
        },
        neutral: {
          50: 'rgb(var(--color-neutral-50))',
          100: 'rgb(var(--color-neutral-100))',
          200: 'rgb(var(--color-neutral-200))',
          300: 'rgb(var(--color-neutral-300))',
          400: 'rgb(var(--color-neutral-400))',
          500: 'rgb(var(--color-neutral-500))',
          600: 'rgb(var(--color-neutral-600))',
          700: 'rgb(var(--color-neutral-700))',
          800: 'rgb(var(--color-neutral-800))',
          900: 'rgb(var(--color-neutral-900))',
          950: 'rgb(var(--color-neutral-950))',
        },
      },
      boxShadow: {
        'soft': '0 2px 10px rgba(0, 0, 0, 0.05)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.08)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
      },
    },
  },
  plugins: [],
};
