import { useState } from 'react';
import { Search, ChefHat, Bath, Bed, Sofa, Flower, Lamp } from 'lucide-react';

interface FurnitureCategory {
  name: string;
  icon: React.ComponentType<any>;
  key: string;
  items: FurnitureTemplate[];
}

interface FurnitureTemplate {
  id: string;
  name: string;
  type: string;
  category: string;
  thumbnail: string;
  dimensions: {
    width: number;
    height: number;
    depth: number;
  };
  defaultMaterial: string;
  defaultColor: string;
  shape: 'box' | 'cylinder' | 'sphere' | 'complex';
}

interface ExpandedFurnitureLibraryProps {
  onAddFurniture: (furniture: {
    type: string;
    name: string;
    dimensions: { width: number; height: number; depth: number };
    material: string;
    color: string;
    shape: 'box' | 'cylinder' | 'sphere' | 'complex';
  }) => void;
}

const furnitureCategories: FurnitureCategory[] = [
  {
    name: 'Living Room',
    icon: Sofa,
    key: 'living-room',
    items: [
      // Seating
      {
        id: 'sofa-3seat',
        name: '3-Seat Sofa',
        type: 'sofa',
        category: 'living-room',
        thumbnail: '🛋️',
        dimensions: { width: 2.2, height: 0.8, depth: 0.9 },
        defaultMaterial: 'fabric',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'sofa-2seat',
        name: '2-Seat Loveseat',
        type: 'loveseat',
        category: 'living-room',
        thumbnail: '🛋️',
        dimensions: { width: 1.5, height: 0.8, depth: 0.9 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'sectional-sofa',
        name: 'L-Shaped Sectional',
        type: 'sectional',
        category: 'living-room',
        thumbnail: '🛋️',
        dimensions: { width: 2.5, height: 0.8, depth: 2.5 },
        defaultMaterial: 'leather',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
      {
        id: 'armchair-modern',
        name: 'Modern Armchair',
        type: 'armchair',
        category: 'living-room',
        thumbnail: '🪑',
        dimensions: { width: 0.8, height: 0.9, depth: 0.8 },
        defaultMaterial: 'leather',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'recliner',
        name: 'Reclining Chair',
        type: 'recliner',
        category: 'living-room',
        thumbnail: '🪑',
        dimensions: { width: 1.0, height: 1.1, depth: 1.2 },
        defaultMaterial: 'leather',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'chaise-lounge',
        name: 'Chaise Lounge',
        type: 'chaise-lounge',
        category: 'living-room',
        thumbnail: '🛋️',
        dimensions: { width: 1.8, height: 0.8, depth: 0.7 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'bean-bag',
        name: 'Bean Bag Chair',
        type: 'bean-bag',
        category: 'living-room',
        thumbnail: '🪑',
        dimensions: { width: 0.8, height: 0.6, depth: 0.8 },
        defaultMaterial: 'fabric',
        defaultColor: '#8B4513',
        shape: 'sphere',
      },
      {
        id: 'ottoman',
        name: 'Ottoman',
        type: 'ottoman',
        category: 'living-room',
        thumbnail: '🪑',
        dimensions: { width: 0.6, height: 0.4, depth: 0.6 },
        defaultMaterial: 'fabric',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'accent-chair',
        name: 'Accent Chair',
        type: 'accent-chair',
        category: 'living-room',
        thumbnail: '🪑',
        dimensions: { width: 0.7, height: 0.9, depth: 0.7 },
        defaultMaterial: 'velvet',
        defaultColor: '#800080',
        shape: 'complex',
      },
      {
        id: 'swivel-chair',
        name: 'Swivel Chair',
        type: 'swivel-chair',
        category: 'living-room',
        thumbnail: '🪑',
        dimensions: { width: 0.6, height: 0.9, depth: 0.6 },
        defaultMaterial: 'leather',
        defaultColor: '#654321',
        shape: 'complex',
      },
      // Tables
      {
        id: 'coffee-table-round',
        name: 'Round Coffee Table',
        type: 'coffee-table',
        category: 'living-room',
        thumbnail: '⭕',
        dimensions: { width: 1.0, height: 0.4, depth: 1.0 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'coffee-table-glass',
        name: 'Glass Coffee Table',
        type: 'coffee-table',
        category: 'living-room',
        thumbnail: '🔳',
        dimensions: { width: 1.2, height: 0.4, depth: 0.6 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'box',
      },
      {
        id: 'coffee-table-marble',
        name: 'Marble Coffee Table',
        type: 'coffee-table',
        category: 'living-room',
        thumbnail: '🔳',
        dimensions: { width: 1.1, height: 0.45, depth: 0.7 },
        defaultMaterial: 'marble',
        defaultColor: '#F5F5DC',
        shape: 'box',
      },
      {
        id: 'nesting-tables',
        name: 'Nesting Tables Set',
        type: 'nesting-tables',
        category: 'living-room',
        thumbnail: '📱',
        dimensions: { width: 0.8, height: 0.5, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'side-table',
        name: 'Side Table',
        type: 'side-table',
        category: 'living-room',
        thumbnail: '📱',
        dimensions: { width: 0.5, height: 0.6, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'console-table',
        name: 'Console Table',
        type: 'console-table',
        category: 'living-room',
        thumbnail: '📺',
        dimensions: { width: 1.2, height: 0.8, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'c-table',
        name: 'C-Shaped Side Table',
        type: 'c-table',
        category: 'living-room',
        thumbnail: '📱',
        dimensions: { width: 0.4, height: 0.6, depth: 0.6 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'complex',
      },
      // Storage & Entertainment
      {
        id: 'tv-stand-modern',
        name: 'Modern TV Stand',
        type: 'tv-stand',
        category: 'living-room',
        thumbnail: '📺',
        dimensions: { width: 1.5, height: 0.5, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#2D3748',
        shape: 'box',
      },
      {
        id: 'entertainment-center',
        name: 'Entertainment Center',
        type: 'entertainment-center',
        category: 'living-room',
        thumbnail: '📺',
        dimensions: { width: 2.0, height: 1.8, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'floating-tv-unit',
        name: 'Floating TV Unit',
        type: 'floating-tv-unit',
        category: 'living-room',
        thumbnail: '📺',
        dimensions: { width: 1.8, height: 0.4, depth: 0.35 },
        defaultMaterial: 'wood',
        defaultColor: '#4A5568',
        shape: 'box',
      },
      {
        id: 'bookshelf-tall',
        name: 'Tall Bookshelf',
        type: 'bookshelf',
        category: 'living-room',
        thumbnail: '📚',
        dimensions: { width: 0.8, height: 2.0, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'ladder-bookshelf',
        name: 'Ladder Bookshelf',
        type: 'ladder-bookshelf',
        category: 'living-room',
        thumbnail: '📚',
        dimensions: { width: 0.6, height: 1.8, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'corner-bookshelf',
        name: 'Corner Bookshelf',
        type: 'corner-bookshelf',
        category: 'living-room',
        thumbnail: '📚',
        dimensions: { width: 0.8, height: 1.8, depth: 0.8 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'storage-cabinet',
        name: 'Storage Cabinet',
        type: 'storage-cabinet',
        category: 'living-room',
        thumbnail: '🗃️',
        dimensions: { width: 1.0, height: 0.9, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'display-cabinet',
        name: 'Glass Display Cabinet',
        type: 'display-cabinet',
        category: 'living-room',
        thumbnail: '🗃️',
        dimensions: { width: 0.8, height: 1.6, depth: 0.4 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'box',
      },
      {
        id: 'storage-ottoman',
        name: 'Storage Ottoman',
        type: 'storage-ottoman',
        category: 'living-room',
        thumbnail: '🗃️',
        dimensions: { width: 0.8, height: 0.4, depth: 0.4 },
        defaultMaterial: 'fabric',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'sideboard',
        name: 'Sideboard',
        type: 'sideboard',
        category: 'living-room',
        thumbnail: '🗃️',
        dimensions: { width: 1.6, height: 0.8, depth: 0.45 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
    ],
  },
  {
    name: 'Kitchen',
    icon: ChefHat,
    key: 'kitchen',
    items: [
      // Dining Tables
      {
        id: 'dining-table-rect',
        name: 'Rectangular Dining Table',
        type: 'dining-table',
        category: 'kitchen',
        thumbnail: '🍽️',
        dimensions: { width: 1.8, height: 0.75, depth: 0.9 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'dining-table-round',
        name: 'Round Dining Table',
        type: 'dining-table',
        category: 'kitchen',
        thumbnail: '⭕',
        dimensions: { width: 1.2, height: 0.75, depth: 1.2 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'dining-table-oval',
        name: 'Oval Dining Table',
        type: 'dining-table',
        category: 'kitchen',
        thumbnail: '🍽️',
        dimensions: { width: 2.0, height: 0.75, depth: 1.0 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'extendable-dining-table',
        name: 'Extendable Dining Table',
        type: 'extendable-table',
        category: 'kitchen',
        thumbnail: '🍽️',
        dimensions: { width: 2.2, height: 0.75, depth: 1.0 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'counter-height-table',
        name: 'Counter Height Table',
        type: 'counter-table',
        category: 'kitchen',
        thumbnail: '🍽️',
        dimensions: { width: 1.2, height: 0.9, depth: 0.8 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'breakfast-nook',
        name: 'Breakfast Nook Table',
        type: 'breakfast-table',
        category: 'kitchen',
        thumbnail: '☕',
        dimensions: { width: 1.0, height: 0.75, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'bistro-table',
        name: 'Bistro Table',
        type: 'bistro-table',
        category: 'kitchen',
        thumbnail: '☕',
        dimensions: { width: 0.8, height: 0.75, depth: 0.8 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'cylinder',
      },
      // Seating
      {
        id: 'dining-chair-wood',
        name: 'Wooden Dining Chair',
        type: 'dining-chair',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.5, height: 0.9, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
      {
        id: 'dining-chair-upholstered',
        name: 'Upholstered Dining Chair',
        type: 'dining-chair',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.5, height: 0.9, depth: 0.5 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'windsor-chair',
        name: 'Windsor Chair',
        type: 'windsor-chair',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.5, height: 0.95, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'parsons-chair',
        name: 'Parsons Chair',
        type: 'parsons-chair',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.5, height: 0.9, depth: 0.6 },
        defaultMaterial: 'fabric',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'captain-chair',
        name: 'Captain Chair',
        type: 'captain-chair',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.6, height: 0.9, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
      {
        id: 'dining-bench',
        name: 'Dining Bench',
        type: 'dining-bench',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 1.2, height: 0.45, depth: 0.35 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'bar-stool-wood',
        name: 'Wooden Bar Stool',
        type: 'bar-stool',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.4, height: 1.1, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'bar-stool-metal',
        name: 'Metal Bar Stool',
        type: 'bar-stool',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.4, height: 1.1, depth: 0.4 },
        defaultMaterial: 'metal',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'swivel-bar-stool',
        name: 'Swivel Bar Stool',
        type: 'swivel-bar-stool',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.4, height: 1.1, depth: 0.4 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'complex',
      },
      {
        id: 'counter-stool',
        name: 'Counter Height Stool',
        type: 'counter-stool',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.4, height: 0.9, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
      {
        id: 'backless-stool',
        name: 'Backless Stool',
        type: 'backless-stool',
        category: 'kitchen',
        thumbnail: '🪑',
        dimensions: { width: 0.35, height: 0.75, depth: 0.35 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'cylinder',
      },
      // Kitchen Islands & Storage
      {
        id: 'kitchen-island-large',
        name: 'Large Kitchen Island',
        type: 'kitchen-island',
        category: 'kitchen',
        thumbnail: '🏠',
        dimensions: { width: 2.0, height: 0.9, depth: 1.0 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'kitchen-island-small',
        name: 'Small Kitchen Island',
        type: 'kitchen-island',
        category: 'kitchen',
        thumbnail: '🏠',
        dimensions: { width: 1.5, height: 0.9, depth: 0.8 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'kitchen-cart',
        name: 'Kitchen Cart',
        type: 'kitchen-cart',
        category: 'kitchen',
        thumbnail: '🛒',
        dimensions: { width: 0.8, height: 0.9, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'rolling-cart',
        name: 'Rolling Kitchen Cart',
        type: 'rolling-cart',
        category: 'kitchen',
        thumbnail: '🛒',
        dimensions: { width: 0.6, height: 0.9, depth: 0.4 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'box',
      },
      {
        id: 'bar-cart',
        name: 'Bar Cart',
        type: 'bar-cart',
        category: 'kitchen',
        thumbnail: '🍷',
        dimensions: { width: 0.8, height: 0.9, depth: 0.4 },
        defaultMaterial: 'metal',
        defaultColor: '#FFD700',
        shape: 'box',
      },
      {
        id: 'pantry-cabinet',
        name: 'Pantry Cabinet',
        type: 'pantry-cabinet',
        category: 'kitchen',
        thumbnail: '🗃️',
        dimensions: { width: 0.6, height: 2.0, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'spice-rack',
        name: 'Spice Rack',
        type: 'spice-rack',
        category: 'kitchen',
        thumbnail: '🧂',
        dimensions: { width: 0.4, height: 0.6, depth: 0.15 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'wine-rack',
        name: 'Wine Rack',
        type: 'wine-rack',
        category: 'kitchen',
        thumbnail: '🍷',
        dimensions: { width: 0.4, height: 1.2, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'microwave-stand',
        name: 'Microwave Stand',
        type: 'microwave-stand',
        category: 'kitchen',
        thumbnail: '🏠',
        dimensions: { width: 0.6, height: 1.0, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'kitchen-hutch',
        name: 'Kitchen Hutch',
        type: 'kitchen-hutch',
        category: 'kitchen',
        thumbnail: '🗃️',
        dimensions: { width: 1.2, height: 2.0, depth: 0.45 },
        defaultMaterial: 'wood',
        defaultColor: '#F5F5DC',
        shape: 'box',
      },
    ],
  },
  {
    name: 'Bedroom',
    icon: Bed,
    key: 'bedroom',
    items: [
      // Beds
      {
        id: 'bed-king',
        name: 'King Size Bed',
        type: 'bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.9, height: 0.6, depth: 2.0 },
        defaultMaterial: 'fabric',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'bed-queen',
        name: 'Queen Size Bed',
        type: 'bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.6, height: 0.6, depth: 2.0 },
        defaultMaterial: 'fabric',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'bed-double',
        name: 'Double Bed',
        type: 'bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.4, height: 0.6, depth: 2.0 },
        defaultMaterial: 'fabric',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'bed-single',
        name: 'Single Bed',
        type: 'bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.0, height: 0.6, depth: 2.0 },
        defaultMaterial: 'fabric',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'bunk-bed',
        name: 'Bunk Bed',
        type: 'bunk-bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.0, height: 1.8, depth: 2.0 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
      {
        id: 'loft-bed',
        name: 'Loft Bed',
        type: 'loft-bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.0, height: 1.8, depth: 2.0 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'daybed',
        name: 'Daybed',
        type: 'daybed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.0, height: 0.6, depth: 2.0 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'futon',
        name: 'Futon',
        type: 'futon',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.4, height: 0.4, depth: 1.9 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'platform-bed',
        name: 'Platform Bed',
        type: 'platform-bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.6, height: 0.3, depth: 2.0 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'storage-bed',
        name: 'Storage Bed',
        type: 'storage-bed',
        category: 'bedroom',
        thumbnail: '🛏️',
        dimensions: { width: 1.6, height: 0.7, depth: 2.0 },
        defaultMaterial: 'fabric',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      // Storage
      {
        id: 'nightstand-modern',
        name: 'Modern Nightstand',
        type: 'nightstand',
        category: 'bedroom',
        thumbnail: '🏠',
        dimensions: { width: 0.4, height: 0.6, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'nightstand-floating',
        name: 'Floating Nightstand',
        type: 'nightstand',
        category: 'bedroom',
        thumbnail: '📱',
        dimensions: { width: 0.5, height: 0.15, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'nightstand-drawer',
        name: '2-Drawer Nightstand',
        type: 'nightstand',
        category: 'bedroom',
        thumbnail: '🏠',
        dimensions: { width: 0.45, height: 0.65, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'nightstand-round',
        name: 'Round Nightstand',
        type: 'nightstand',
        category: 'bedroom',
        thumbnail: '⭕',
        dimensions: { width: 0.4, height: 0.6, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'wardrobe-large',
        name: 'Large Wardrobe',
        type: 'wardrobe',
        category: 'bedroom',
        thumbnail: '👗',
        dimensions: { width: 1.5, height: 2.2, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'wardrobe-sliding',
        name: 'Sliding Door Wardrobe',
        type: 'sliding-wardrobe',
        category: 'bedroom',
        thumbnail: '👗',
        dimensions: { width: 2.0, height: 2.2, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'walk-in-closet',
        name: 'Walk-in Closet System',
        type: 'closet-system',
        category: 'bedroom',
        thumbnail: '👗',
        dimensions: { width: 2.0, height: 2.2, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'armoire',
        name: 'Armoire',
        type: 'armoire',
        category: 'bedroom',
        thumbnail: '👗',
        dimensions: { width: 1.2, height: 2.0, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'dresser-6drawer',
        name: '6-Drawer Dresser',
        type: 'dresser',
        category: 'bedroom',
        thumbnail: '🗃️',
        dimensions: { width: 1.5, height: 0.8, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'dresser-tall',
        name: 'Tall Dresser',
        type: 'tall-dresser',
        category: 'bedroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.8, height: 1.4, depth: 0.45 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'chest-drawers',
        name: 'Chest of Drawers',
        type: 'chest-drawers',
        category: 'bedroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.8, height: 1.2, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'storage-bench',
        name: 'Storage Bench',
        type: 'storage-bench',
        category: 'bedroom',
        thumbnail: '🪑',
        dimensions: { width: 1.2, height: 0.45, depth: 0.4 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'box',
      },
      {
        id: 'cedar-chest',
        name: 'Cedar Chest',
        type: 'cedar-chest',
        category: 'bedroom',
        thumbnail: '🗃️',
        dimensions: { width: 1.0, height: 0.5, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      // Seating
      {
        id: 'bedroom-chair',
        name: 'Bedroom Accent Chair',
        type: 'accent-chair',
        category: 'bedroom',
        thumbnail: '🪑',
        dimensions: { width: 0.7, height: 0.9, depth: 0.7 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'reading-chair',
        name: 'Reading Chair',
        type: 'reading-chair',
        category: 'bedroom',
        thumbnail: '🪑',
        dimensions: { width: 0.8, height: 1.0, depth: 0.8 },
        defaultMaterial: 'fabric',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
      {
        id: 'vanity-stool',
        name: 'Vanity Stool',
        type: 'vanity-stool',
        category: 'bedroom',
        thumbnail: '🪑',
        dimensions: { width: 0.4, height: 0.5, depth: 0.4 },
        defaultMaterial: 'fabric',
        defaultColor: '#F5F5DC',
        shape: 'cylinder',
      },
      {
        id: 'bedroom-bench',
        name: 'Bedroom Bench',
        type: 'bedroom-bench',
        category: 'bedroom',
        thumbnail: '🪑',
        dimensions: { width: 1.2, height: 0.45, depth: 0.35 },
        defaultMaterial: 'fabric',
        defaultColor: '#2D3748',
        shape: 'box',
      },
      // Vanity & Mirrors
      {
        id: 'vanity-table',
        name: 'Vanity Table',
        type: 'vanity-table',
        category: 'bedroom',
        thumbnail: '💄',
        dimensions: { width: 1.2, height: 0.75, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#F5F5DC',
        shape: 'box',
      },
      {
        id: 'vanity-with-mirror',
        name: 'Vanity with Mirror',
        type: 'vanity-with-mirror',
        category: 'bedroom',
        thumbnail: '💄',
        dimensions: { width: 1.2, height: 1.6, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'makeup-vanity',
        name: 'Makeup Vanity',
        type: 'makeup-vanity',
        category: 'bedroom',
        thumbnail: '💄',
        dimensions: { width: 1.0, height: 0.75, depth: 0.45 },
        defaultMaterial: 'wood',
        defaultColor: '#FFFFFF',
        shape: 'box',
      },
      {
        id: 'full-length-mirror',
        name: 'Full Length Mirror',
        type: 'mirror',
        category: 'bedroom',
        thumbnail: '🪞',
        dimensions: { width: 0.6, height: 1.8, depth: 0.05 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'box',
      },
      {
        id: 'standing-mirror',
        name: 'Standing Mirror',
        type: 'standing-mirror',
        category: 'bedroom',
        thumbnail: '🪞',
        dimensions: { width: 0.6, height: 1.6, depth: 0.6 },
        defaultMaterial: 'glass',
        defaultColor: '#FFD700',
        shape: 'complex',
      },
      {
        id: 'tri-fold-mirror',
        name: 'Tri-Fold Mirror',
        type: 'tri-fold-mirror',
        category: 'bedroom',
        thumbnail: '🪞',
        dimensions: { width: 0.8, height: 0.6, depth: 0.1 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'complex',
      },
    ],
  },
  {
    name: 'Bathroom',
    icon: Bath,
    key: 'bathroom',
    items: [
      // Vanities
      {
        id: 'double-vanity',
        name: 'Double Sink Vanity',
        type: 'vanity',
        category: 'bathroom',
        thumbnail: '🚿',
        dimensions: { width: 1.5, height: 0.85, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#F5F5DC',
        shape: 'box',
      },
      {
        id: 'single-vanity',
        name: 'Single Sink Vanity',
        type: 'vanity',
        category: 'bathroom',
        thumbnail: '🚿',
        dimensions: { width: 0.9, height: 0.85, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'floating-vanity',
        name: 'Floating Vanity',
        type: 'vanity',
        category: 'bathroom',
        thumbnail: '🚿',
        dimensions: { width: 1.0, height: 0.6, depth: 0.45 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'corner-vanity',
        name: 'Corner Vanity',
        type: 'vanity',
        category: 'bathroom',
        thumbnail: '🚿',
        dimensions: { width: 0.8, height: 0.85, depth: 0.8 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'vessel-sink-vanity',
        name: 'Vessel Sink Vanity',
        type: 'vessel-vanity',
        category: 'bathroom',
        thumbnail: '🚿',
        dimensions: { width: 1.0, height: 0.8, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'pedestal-sink',
        name: 'Pedestal Sink',
        type: 'pedestal-sink',
        category: 'bathroom',
        thumbnail: '🚿',
        dimensions: { width: 0.6, height: 0.85, depth: 0.5 },
        defaultMaterial: 'ceramic',
        defaultColor: '#FFFFFF',
        shape: 'complex',
      },
      // Storage
      {
        id: 'linen-tower',
        name: 'Linen Tower',
        type: 'linen-tower',
        category: 'bathroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.4, height: 1.8, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#FFFFFF',
        shape: 'box',
      },
      {
        id: 'linen-cabinet',
        name: 'Linen Cabinet',
        type: 'linen-cabinet',
        category: 'bathroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.6, height: 1.5, depth: 0.35 },
        defaultMaterial: 'wood',
        defaultColor: '#F5F5DC',
        shape: 'box',
      },
      {
        id: 'medicine-cabinet',
        name: 'Medicine Cabinet',
        type: 'medicine-cabinet',
        category: 'bathroom',
        thumbnail: '💊',
        dimensions: { width: 0.6, height: 0.8, depth: 0.15 },
        defaultMaterial: 'wood',
        defaultColor: '#F5F5DC',
        shape: 'box',
      },
      {
        id: 'over-toilet-cabinet',
        name: 'Over-Toilet Cabinet',
        type: 'over-toilet-cabinet',
        category: 'bathroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.7, height: 1.0, depth: 0.25 },
        defaultMaterial: 'wood',
        defaultColor: '#FFFFFF',
        shape: 'box',
      },
      {
        id: 'bathroom-shelf-unit',
        name: 'Bathroom Shelf Unit',
        type: 'shelf-unit',
        category: 'bathroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.8, height: 1.6, depth: 0.25 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'box',
      },
      {
        id: 'corner-shelf',
        name: 'Corner Shelf',
        type: 'corner-shelf',
        category: 'bathroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.3, height: 1.2, depth: 0.3 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'complex',
      },
      {
        id: 'wall-cabinet',
        name: 'Wall Cabinet',
        type: 'wall-cabinet',
        category: 'bathroom',
        thumbnail: '🗃️',
        dimensions: { width: 0.8, height: 0.6, depth: 0.2 },
        defaultMaterial: 'wood',
        defaultColor: '#FFFFFF',
        shape: 'box',
      },
      // Mirrors
      {
        id: 'round-mirror',
        name: 'Round Bathroom Mirror',
        type: 'mirror',
        category: 'bathroom',
        thumbnail: '⭕',
        dimensions: { width: 0.6, height: 0.6, depth: 0.05 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'cylinder',
      },
      {
        id: 'rectangular-mirror',
        name: 'Rectangular Mirror',
        type: 'mirror',
        category: 'bathroom',
        thumbnail: '🪞',
        dimensions: { width: 0.8, height: 1.0, depth: 0.05 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'box',
      },
      {
        id: 'vanity-mirror',
        name: 'Vanity Mirror',
        type: 'vanity-mirror',
        category: 'bathroom',
        thumbnail: '🪞',
        dimensions: { width: 1.0, height: 0.8, depth: 0.05 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'box',
      },
      {
        id: 'oval-mirror',
        name: 'Oval Mirror',
        type: 'oval-mirror',
        category: 'bathroom',
        thumbnail: '🪞',
        dimensions: { width: 0.6, height: 0.8, depth: 0.05 },
        defaultMaterial: 'glass',
        defaultColor: '#FFD700',
        shape: 'complex',
      },
      {
        id: 'led-mirror',
        name: 'LED Lighted Mirror',
        type: 'led-mirror',
        category: 'bathroom',
        thumbnail: '🪞',
        dimensions: { width: 0.8, height: 1.0, depth: 0.08 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'box',
      },
      // Accessories & Seating
      {
        id: 'towel-rack',
        name: 'Towel Rack',
        type: 'towel-rack',
        category: 'bathroom',
        thumbnail: '🏠',
        dimensions: { width: 0.6, height: 0.1, depth: 0.2 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'box',
      },
      {
        id: 'towel-warmer',
        name: 'Heated Towel Warmer',
        type: 'towel-warmer',
        category: 'bathroom',
        thumbnail: '🏠',
        dimensions: { width: 0.5, height: 0.8, depth: 0.15 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'box',
      },
      {
        id: 'hamper',
        name: 'Laundry Hamper',
        type: 'hamper',
        category: 'bathroom',
        thumbnail: '🧺',
        dimensions: { width: 0.4, height: 0.6, depth: 0.4 },
        defaultMaterial: 'fabric',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'bathroom-stool',
        name: 'Bathroom Stool',
        type: 'bathroom-stool',
        category: 'bathroom',
        thumbnail: '🪑',
        dimensions: { width: 0.3, height: 0.4, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#F5F5DC',
        shape: 'cylinder',
      },
      {
        id: 'shower-bench',
        name: 'Shower Bench',
        type: 'shower-bench',
        category: 'bathroom',
        thumbnail: '🪑',
        dimensions: { width: 0.8, height: 0.4, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'bathroom-scale',
        name: 'Bathroom Scale',
        type: 'scale',
        category: 'bathroom',
        thumbnail: '⚖️',
        dimensions: { width: 0.3, height: 0.05, depth: 0.3 },
        defaultMaterial: 'glass',
        defaultColor: '#2D3748',
        shape: 'box',
      },
      {
        id: 'toilet-paper-stand',
        name: 'Toilet Paper Stand',
        type: 'tp-stand',
        category: 'bathroom',
        thumbnail: '🧻',
        dimensions: { width: 0.2, height: 0.7, depth: 0.2 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'cylinder',
      },
    ],
  },
  {
    name: 'Office',
    icon: Lamp,
    key: 'office',
    items: [
      // Desks
      {
        id: 'executive-desk',
        name: 'Executive Desk',
        type: 'desk',
        category: 'office',
        thumbnail: '🖥️',
        dimensions: { width: 1.8, height: 0.75, depth: 0.9 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'computer-desk',
        name: 'Computer Desk',
        type: 'computer-desk',
        category: 'office',
        thumbnail: '🖥️',
        dimensions: { width: 1.2, height: 0.75, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'standing-desk',
        name: 'Standing Desk',
        type: 'standing-desk',
        category: 'office',
        thumbnail: '🖥️',
        dimensions: { width: 1.4, height: 1.1, depth: 0.7 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'adjustable-desk',
        name: 'Height Adjustable Desk',
        type: 'adjustable-desk',
        category: 'office',
        thumbnail: '🖥️',
        dimensions: { width: 1.6, height: 0.9, depth: 0.8 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'box',
      },
      {
        id: 'corner-desk',
        name: 'Corner Desk',
        type: 'corner-desk',
        category: 'office',
        thumbnail: '🖥️',
        dimensions: { width: 1.5, height: 0.75, depth: 1.5 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'l-shaped-desk',
        name: 'L-Shaped Desk',
        type: 'l-shaped-desk',
        category: 'office',
        thumbnail: '🖥️',
        dimensions: { width: 1.8, height: 0.75, depth: 1.4 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'writing-desk',
        name: 'Writing Desk',
        type: 'writing-desk',
        category: 'office',
        thumbnail: '✍️',
        dimensions: { width: 1.2, height: 0.75, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'secretary-desk',
        name: 'Secretary Desk',
        type: 'secretary-desk',
        category: 'office',
        thumbnail: '✍️',
        dimensions: { width: 1.0, height: 1.8, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'gaming-desk',
        name: 'Gaming Desk',
        type: 'gaming-desk',
        category: 'office',
        thumbnail: '🎮',
        dimensions: { width: 1.4, height: 0.75, depth: 0.7 },
        defaultMaterial: 'metal',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'drafting-table',
        name: 'Drafting Table',
        type: 'drafting-table',
        category: 'office',
        thumbnail: '📐',
        dimensions: { width: 1.2, height: 0.9, depth: 0.8 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      // Chairs
      {
        id: 'executive-chair',
        name: 'Executive Office Chair',
        type: 'office-chair',
        category: 'office',
        thumbnail: '🪑',
        dimensions: { width: 0.6, height: 1.2, depth: 0.6 },
        defaultMaterial: 'leather',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'ergonomic-chair',
        name: 'Ergonomic Chair',
        type: 'office-chair',
        category: 'office',
        thumbnail: '🪑',
        dimensions: { width: 0.6, height: 1.1, depth: 0.6 },
        defaultMaterial: 'mesh',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'task-chair',
        name: 'Task Chair',
        type: 'task-chair',
        category: 'office',
        thumbnail: '🪑',
        dimensions: { width: 0.5, height: 1.0, depth: 0.5 },
        defaultMaterial: 'fabric',
        defaultColor: '#708090',
        shape: 'complex',
      },
      {
        id: 'guest-chair',
        name: 'Guest Chair',
        type: 'guest-chair',
        category: 'office',
        thumbnail: '🪑',
        dimensions: { width: 0.6, height: 0.9, depth: 0.6 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      {
        id: 'conference-chair',
        name: 'Conference Chair',
        type: 'conference-chair',
        category: 'office',
        thumbnail: '🪑',
        dimensions: { width: 0.6, height: 1.0, depth: 0.6 },
        defaultMaterial: 'leather',
        defaultColor: '#654321',
        shape: 'complex',
      },
      {
        id: 'drafting-chair',
        name: 'Drafting Chair',
        type: 'drafting-chair',
        category: 'office',
        thumbnail: '🪑',
        dimensions: { width: 0.5, height: 1.3, depth: 0.5 },
        defaultMaterial: 'fabric',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'gaming-chair',
        name: 'Gaming Chair',
        type: 'gaming-chair',
        category: 'office',
        thumbnail: '🎮',
        dimensions: { width: 0.7, height: 1.3, depth: 0.7 },
        defaultMaterial: 'leather',
        defaultColor: '#8B0000',
        shape: 'complex',
      },
      {
        id: 'kneeling-chair',
        name: 'Kneeling Chair',
        type: 'kneeling-chair',
        category: 'office',
        thumbnail: '🪑',
        dimensions: { width: 0.5, height: 1.2, depth: 0.8 },
        defaultMaterial: 'fabric',
        defaultColor: '#4A5568',
        shape: 'complex',
      },
      // Storage
      {
        id: 'tall-bookshelf',
        name: 'Tall Bookshelf',
        type: 'bookshelf',
        category: 'office',
        thumbnail: '📚',
        dimensions: { width: 0.8, height: 2.0, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'modular-bookshelf',
        name: 'Modular Bookshelf',
        type: 'bookshelf',
        category: 'office',
        thumbnail: '📚',
        dimensions: { width: 1.2, height: 1.8, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'corner-bookshelf',
        name: 'Corner Bookshelf',
        type: 'corner-bookshelf',
        category: 'office',
        thumbnail: '📚',
        dimensions: { width: 0.6, height: 1.8, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'wall-mounted-shelf',
        name: 'Wall Mounted Shelf',
        type: 'wall-shelf',
        category: 'office',
        thumbnail: '📚',
        dimensions: { width: 1.0, height: 0.05, depth: 0.25 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'filing-cabinet-4drawer',
        name: '4-Drawer Filing Cabinet',
        type: 'filing-cabinet',
        category: 'office',
        thumbnail: '🗃️',
        dimensions: { width: 0.4, height: 1.3, depth: 0.6 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'box',
      },
      {
        id: 'filing-cabinet-2drawer',
        name: '2-Drawer Filing Cabinet',
        type: 'filing-cabinet',
        category: 'office',
        thumbnail: '🗃️',
        dimensions: { width: 0.4, height: 0.7, depth: 0.6 },
        defaultMaterial: 'metal',
        defaultColor: '#4A5568',
        shape: 'box',
      },
      {
        id: 'lateral-filing-cabinet',
        name: 'Lateral Filing Cabinet',
        type: 'filing-cabinet',
        category: 'office',
        thumbnail: '🗃️',
        dimensions: { width: 0.9, height: 0.7, depth: 0.6 },
        defaultMaterial: 'metal',
        defaultColor: '#4A5568',
        shape: 'box',
      },
      {
        id: 'mobile-pedestal',
        name: 'Mobile Pedestal',
        type: 'mobile-pedestal',
        category: 'office',
        thumbnail: '🗃️',
        dimensions: { width: 0.4, height: 0.6, depth: 0.5 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'box',
      },
      {
        id: 'credenza',
        name: 'Office Credenza',
        type: 'credenza',
        category: 'office',
        thumbnail: '🗃️',
        dimensions: { width: 1.5, height: 0.8, depth: 0.5 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'storage-cabinet',
        name: 'Storage Cabinet',
        type: 'storage-cabinet',
        category: 'office',
        thumbnail: '🗃️',
        dimensions: { width: 0.8, height: 1.8, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      // Meeting & Collaboration
      {
        id: 'conference-table',
        name: 'Conference Table',
        type: 'conference-table',
        category: 'office',
        thumbnail: '🍽️',
        dimensions: { width: 2.4, height: 0.75, depth: 1.2 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'round-conference-table',
        name: 'Round Conference Table',
        type: 'round-conference-table',
        category: 'office',
        thumbnail: '⭕',
        dimensions: { width: 1.5, height: 0.75, depth: 1.5 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'standing-meeting-table',
        name: 'Standing Meeting Table',
        type: 'standing-meeting-table',
        category: 'office',
        thumbnail: '🍽️',
        dimensions: { width: 1.8, height: 1.1, depth: 0.9 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'box',
      },
      {
        id: 'whiteboard',
        name: 'Whiteboard',
        type: 'whiteboard',
        category: 'office',
        thumbnail: '⬜',
        dimensions: { width: 1.2, height: 0.9, depth: 0.05 },
        defaultMaterial: 'metal',
        defaultColor: '#FFFFFF',
        shape: 'box',
      },
      {
        id: 'flip-chart',
        name: 'Flip Chart Stand',
        type: 'flip-chart',
        category: 'office',
        thumbnail: '📋',
        dimensions: { width: 0.7, height: 1.8, depth: 0.6 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'complex',
      },
      {
        id: 'presentation-easel',
        name: 'Presentation Easel',
        type: 'easel',
        category: 'office',
        thumbnail: '🎨',
        dimensions: { width: 0.6, height: 1.6, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
    ],
  },
  {
    name: 'Decor & Lighting',
    icon: Flower,
    key: 'decor',
    items: [
      // Floor Lamps
      {
        id: 'arc-floor-lamp',
        name: 'Arc Floor Lamp',
        type: 'floor-lamp',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.4, height: 1.8, depth: 1.2 },
        defaultMaterial: 'metal',
        defaultColor: '#FFD700',
        shape: 'complex',
      },
      {
        id: 'tripod-floor-lamp',
        name: 'Tripod Floor Lamp',
        type: 'floor-lamp',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.6, height: 1.6, depth: 0.6 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'complex',
      },
      {
        id: 'torchiere-lamp',
        name: 'Torchiere Lamp',
        type: 'floor-lamp',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.4, height: 1.8, depth: 0.4 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'cylinder',
      },
      {
        id: 'tree-floor-lamp',
        name: 'Tree Floor Lamp',
        type: 'tree-lamp',
        category: 'decor',
        thumbnail: '🌳',
        dimensions: { width: 0.6, height: 1.8, depth: 0.6 },
        defaultMaterial: 'metal',
        defaultColor: '#FFD700',
        shape: 'complex',
      },
      {
        id: 'tower-floor-lamp',
        name: 'Tower Floor Lamp',
        type: 'tower-lamp',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.3, height: 1.6, depth: 0.3 },
        defaultMaterial: 'fabric',
        defaultColor: '#F5F5DC',
        shape: 'cylinder',
      },
      {
        id: 'industrial-floor-lamp',
        name: 'Industrial Floor Lamp',
        type: 'industrial-lamp',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.5, height: 1.7, depth: 0.5 },
        defaultMaterial: 'metal',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'reading-floor-lamp',
        name: 'Reading Floor Lamp',
        type: 'reading-lamp',
        category: 'decor',
        thumbnail: '📖',
        dimensions: { width: 0.4, height: 1.5, depth: 0.4 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'complex',
      },
      // Table Lamps
      {
        id: 'ceramic-table-lamp',
        name: 'Ceramic Table Lamp',
        type: 'table-lamp',
        category: 'decor',
        thumbnail: '🔦',
        dimensions: { width: 0.25, height: 0.6, depth: 0.25 },
        defaultMaterial: 'ceramic',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'crystal-table-lamp',
        name: 'Crystal Table Lamp',
        type: 'table-lamp',
        category: 'decor',
        thumbnail: '🔦',
        dimensions: { width: 0.2, height: 0.7, depth: 0.2 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'complex',
      },
      {
        id: 'bedside-lamp',
        name: 'Bedside Reading Lamp',
        type: 'table-lamp',
        category: 'decor',
        thumbnail: '🔦',
        dimensions: { width: 0.15, height: 0.4, depth: 0.15 },
        defaultMaterial: 'metal',
        defaultColor: '#FFD700',
        shape: 'cylinder',
      },
      {
        id: 'desk-lamp',
        name: 'Adjustable Desk Lamp',
        type: 'desk-lamp',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.2, height: 0.5, depth: 0.3 },
        defaultMaterial: 'metal',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'banker-lamp',
        name: 'Banker\'s Lamp',
        type: 'banker-lamp',
        category: 'decor',
        thumbnail: '🔦',
        dimensions: { width: 0.25, height: 0.4, depth: 0.2 },
        defaultMaterial: 'brass',
        defaultColor: '#FFD700',
        shape: 'complex',
      },
      {
        id: 'tiffany-lamp',
        name: 'Tiffany Style Lamp',
        type: 'tiffany-lamp',
        category: 'decor',
        thumbnail: '🔦',
        dimensions: { width: 0.3, height: 0.6, depth: 0.3 },
        defaultMaterial: 'glass',
        defaultColor: '#4169E1',
        shape: 'complex',
      },
      {
        id: 'buffet-lamp',
        name: 'Buffet Lamp',
        type: 'buffet-lamp',
        category: 'decor',
        thumbnail: '🔦',
        dimensions: { width: 0.15, height: 0.8, depth: 0.15 },
        defaultMaterial: 'ceramic',
        defaultColor: '#F5F5DC',
        shape: 'cylinder',
      },
      // Ceiling Lights
      {
        id: 'chandelier',
        name: 'Crystal Chandelier',
        type: 'chandelier',
        category: 'decor',
        thumbnail: '💎',
        dimensions: { width: 1.0, height: 0.8, depth: 1.0 },
        defaultMaterial: 'crystal',
        defaultColor: '#E0E0E0',
        shape: 'complex',
      },
      {
        id: 'modern-chandelier',
        name: 'Modern Chandelier',
        type: 'modern-chandelier',
        category: 'decor',
        thumbnail: '💎',
        dimensions: { width: 0.8, height: 0.6, depth: 0.8 },
        defaultMaterial: 'metal',
        defaultColor: '#2D3748',
        shape: 'complex',
      },
      {
        id: 'pendant-light',
        name: 'Pendant Light',
        type: 'pendant-light',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.3, height: 0.4, depth: 0.3 },
        defaultMaterial: 'metal',
        defaultColor: '#2D3748',
        shape: 'cylinder',
      },
      {
        id: 'pendant-cluster',
        name: 'Pendant Light Cluster',
        type: 'pendant-cluster',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.8, height: 0.6, depth: 0.8 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'complex',
      },
      {
        id: 'track-lighting',
        name: 'Track Lighting',
        type: 'track-lighting',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 1.2, height: 0.1, depth: 0.1 },
        defaultMaterial: 'metal',
        defaultColor: '#4A5568',
        shape: 'box',
      },
      {
        id: 'recessed-lighting',
        name: 'Recessed Light Fixture',
        type: 'recessed-light',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.15, height: 0.1, depth: 0.15 },
        defaultMaterial: 'metal',
        defaultColor: '#FFFFFF',
        shape: 'cylinder',
      },
      {
        id: 'flush-mount',
        name: 'Flush Mount Ceiling Light',
        type: 'flush-mount',
        category: 'decor',
        thumbnail: '💡',
        dimensions: { width: 0.4, height: 0.15, depth: 0.4 },
        defaultMaterial: 'glass',
        defaultColor: '#E0E0E0',
        shape: 'cylinder',
      },
      // Plants & Planters
      {
        id: 'large-floor-plant',
        name: 'Large Floor Plant',
        type: 'plant-pot',
        category: 'decor',
        thumbnail: '🌿',
        dimensions: { width: 0.4, height: 1.5, depth: 0.4 },
        defaultMaterial: 'ceramic',
        defaultColor: '#228B22',
        shape: 'cylinder',
      },
      {
        id: 'fiddle-leaf-fig',
        name: 'Fiddle Leaf Fig',
        type: 'fiddle-leaf',
        category: 'decor',
        thumbnail: '🌿',
        dimensions: { width: 0.5, height: 1.8, depth: 0.5 },
        defaultMaterial: 'ceramic',
        defaultColor: '#228B22',
        shape: 'cylinder',
      },
      {
        id: 'snake-plant',
        name: 'Snake Plant',
        type: 'snake-plant',
        category: 'decor',
        thumbnail: '🌿',
        dimensions: { width: 0.3, height: 1.0, depth: 0.3 },
        defaultMaterial: 'ceramic',
        defaultColor: '#228B22',
        shape: 'cylinder',
      },
      {
        id: 'small-plant-pot',
        name: 'Small Plant Pot',
        type: 'plant-pot',
        category: 'decor',
        thumbnail: '🪴',
        dimensions: { width: 0.2, height: 0.3, depth: 0.2 },
        defaultMaterial: 'ceramic',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'succulent-garden',
        name: 'Succulent Garden',
        type: 'succulent-garden',
        category: 'decor',
        thumbnail: '🌵',
        dimensions: { width: 0.4, height: 0.2, depth: 0.3 },
        defaultMaterial: 'ceramic',
        defaultColor: '#228B22',
        shape: 'box',
      },
      {
        id: 'hanging-plant',
        name: 'Hanging Plant',
        type: 'hanging-plant',
        category: 'decor',
        thumbnail: '🌿',
        dimensions: { width: 0.3, height: 0.8, depth: 0.3 },
        defaultMaterial: 'ceramic',
        defaultColor: '#228B22',
        shape: 'sphere',
      },
      {
        id: 'plant-stand',
        name: 'Plant Stand',
        type: 'plant-stand',
        category: 'decor',
        thumbnail: '🌿',
        dimensions: { width: 0.3, height: 0.8, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'plant-ladder',
        name: 'Plant Ladder Stand',
        type: 'plant-ladder',
        category: 'decor',
        thumbnail: '🌿',
        dimensions: { width: 0.6, height: 1.2, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'planter-box',
        name: 'Rectangular Planter Box',
        type: 'planter-box',
        category: 'decor',
        thumbnail: '🌿',
        dimensions: { width: 0.8, height: 0.3, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      // Wall Art & Decor
      {
        id: 'large-wall-art',
        name: 'Large Wall Art',
        type: 'wall-art',
        category: 'decor',
        thumbnail: '🖼️',
        dimensions: { width: 1.2, height: 0.8, depth: 0.05 },
        defaultMaterial: 'canvas',
        defaultColor: '#4169E1',
        shape: 'box',
      },
      {
        id: 'abstract-painting',
        name: 'Abstract Painting',
        type: 'abstract-art',
        category: 'decor',
        thumbnail: '🎨',
        dimensions: { width: 0.8, height: 1.0, depth: 0.05 },
        defaultMaterial: 'canvas',
        defaultColor: '#FF6347',
        shape: 'box',
      },
      {
        id: 'photo-gallery',
        name: 'Photo Gallery Set',
        type: 'wall-art',
        category: 'decor',
        thumbnail: '🖼️',
        dimensions: { width: 1.5, height: 1.0, depth: 0.05 },
        defaultMaterial: 'canvas',
        defaultColor: '#2D3748',
        shape: 'box',
      },
      {
        id: 'metal-wall-art',
        name: 'Metal Wall Sculpture',
        type: 'metal-art',
        category: 'decor',
        thumbnail: '🔩',
        dimensions: { width: 0.8, height: 0.8, depth: 0.1 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'complex',
      },
      {
        id: 'wall-mirror-decorative',
        name: 'Decorative Wall Mirror',
        type: 'wall-mirror',
        category: 'decor',
        thumbnail: '🪞',
        dimensions: { width: 0.8, height: 0.8, depth: 0.05 },
        defaultMaterial: 'glass',
        defaultColor: '#FFD700',
        shape: 'cylinder',
      },
      {
        id: 'sunburst-mirror',
        name: 'Sunburst Mirror',
        type: 'sunburst-mirror',
        category: 'decor',
        thumbnail: '☀️',
        dimensions: { width: 0.9, height: 0.9, depth: 0.1 },
        defaultMaterial: 'metal',
        defaultColor: '#FFD700',
        shape: 'complex',
      },
      {
        id: 'wall-shelf',
        name: 'Floating Wall Shelf',
        type: 'wall-shelf',
        category: 'decor',
        thumbnail: '📚',
        dimensions: { width: 0.8, height: 0.05, depth: 0.2 },
        defaultMaterial: 'wood',
        defaultColor: '#8B4513',
        shape: 'box',
      },
      {
        id: 'corner-wall-shelf',
        name: 'Corner Wall Shelf',
        type: 'corner-shelf',
        category: 'decor',
        thumbnail: '📚',
        dimensions: { width: 0.4, height: 0.05, depth: 0.4 },
        defaultMaterial: 'wood',
        defaultColor: '#A0522D',
        shape: 'complex',
      },
      {
        id: 'wall-hooks',
        name: 'Decorative Wall Hooks',
        type: 'wall-hooks',
        category: 'decor',
        thumbnail: '🪝',
        dimensions: { width: 0.6, height: 0.1, depth: 0.1 },
        defaultMaterial: 'metal',
        defaultColor: '#708090',
        shape: 'complex',
      },
      // Decorative Objects
      {
        id: 'decorative-vase',
        name: 'Decorative Vase',
        type: 'vase',
        category: 'decor',
        thumbnail: '🏺',
        dimensions: { width: 0.2, height: 0.4, depth: 0.2 },
        defaultMaterial: 'ceramic',
        defaultColor: '#4169E1',
        shape: 'cylinder',
      },
      {
        id: 'tall-floor-vase',
        name: 'Tall Floor Vase',
        type: 'floor-vase',
        category: 'decor',
        thumbnail: '🏺',
        dimensions: { width: 0.3, height: 0.8, depth: 0.3 },
        defaultMaterial: 'ceramic',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'ceramic-sculpture',
        name: 'Ceramic Sculpture',
        type: 'sculpture',
        category: 'decor',
        thumbnail: '🗿',
        dimensions: { width: 0.25, height: 0.5, depth: 0.25 },
        defaultMaterial: 'ceramic',
        defaultColor: '#F5F5DC',
        shape: 'complex',
      },
      {
        id: 'candles',
        name: 'Candle Set',
        type: 'candles',
        category: 'decor',
        thumbnail: '🕯️',
        dimensions: { width: 0.3, height: 0.2, depth: 0.1 },
        defaultMaterial: 'wax',
        defaultColor: '#F5F5DC',
        shape: 'cylinder',
      },
      {
        id: 'pillar-candles',
        name: 'Pillar Candles',
        type: 'pillar-candles',
        category: 'decor',
        thumbnail: '🕯️',
        dimensions: { width: 0.15, height: 0.3, depth: 0.15 },
        defaultMaterial: 'wax',
        defaultColor: '#FFFFFF',
        shape: 'cylinder',
      },
      {
        id: 'decorative-bowl',
        name: 'Decorative Bowl',
        type: 'decorative-bowl',
        category: 'decor',
        thumbnail: '🍽️',
        dimensions: { width: 0.3, height: 0.1, depth: 0.3 },
        defaultMaterial: 'ceramic',
        defaultColor: '#8B4513',
        shape: 'cylinder',
      },
      {
        id: 'decorative-tray',
        name: 'Decorative Tray',
        type: 'decorative-tray',
        category: 'decor',
        thumbnail: '🍽️',
        dimensions: { width: 0.4, height: 0.05, depth: 0.3 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'table-clock',
        name: 'Table Clock',
        type: 'table-clock',
        category: 'decor',
        thumbnail: '🕐',
        dimensions: { width: 0.15, height: 0.2, depth: 0.1 },
        defaultMaterial: 'metal',
        defaultColor: '#FFD700',
        shape: 'complex',
      },
      {
        id: 'picture-frames',
        name: 'Picture Frame Set',
        type: 'picture-frames',
        category: 'decor',
        thumbnail: '🖼️',
        dimensions: { width: 0.4, height: 0.3, depth: 0.02 },
        defaultMaterial: 'wood',
        defaultColor: '#654321',
        shape: 'box',
      },
      {
        id: 'throw-pillows',
        name: 'Decorative Throw Pillows',
        type: 'throw-pillows',
        category: 'decor',
        thumbnail: '🛋️',
        dimensions: { width: 0.4, height: 0.4, depth: 0.15 },
        defaultMaterial: 'fabric',
        defaultColor: '#4169E1',
        shape: 'box',
      },
    ],
  },
];

const ExpandedFurnitureLibrary = ({ onAddFurniture }: ExpandedFurnitureLibraryProps) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('living-room');

  const handleCategoryChange = (categoryKey: string) => {
    setSelectedCategory(categoryKey);
    setSearchTerm('');
  };

  const filteredItems = furnitureCategories
    .find(cat => cat.key === selectedCategory)?.items
    .filter(item =>
      item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.type.toLowerCase().includes(searchTerm.toLowerCase())
    ) || [];

  const handleAddFurniture = (item: FurnitureTemplate) => {
    onAddFurniture({
      type: item.type,
      name: item.name,
      dimensions: item.dimensions,
      material: item.defaultMaterial,
      color: item.defaultColor,
      shape: item.shape,
    });
  };

  return (
    <div className="h-full flex flex-col">
      {/* Search */}
      <div className="p-4 border-b border-neutral-200">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-neutral-400 w-4 h-4" />
          <input
            type="text"
            placeholder="Search furniture..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
          />
        </div>
      </div>

      {/* Category Filter */}
      <div className="p-4 border-b border-neutral-200">
        <div className="grid grid-cols-2 gap-2">
          {furnitureCategories.map(category => {
            const Icon = category.icon;
            return (
              <button
                key={category.key}
                onClick={() => handleCategoryChange(category.key)}
                className={`flex items-center space-x-2 p-2 rounded-lg text-sm transition-colors ${
                  selectedCategory === category.key
                    ? 'bg-primary-500 text-white'
                    : 'bg-neutral-100 hover:bg-neutral-200 text-neutral-700'
                }`}
              >
                <Icon className="w-4 h-4" />
                <span className="truncate">{category.name}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Furniture Items */}
      <div className="flex-1 overflow-y-auto p-4">
        {filteredItems.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-32 space-y-2">
            <p className="text-sm text-neutral-500">No furniture found</p>
            <p className="text-xs text-neutral-400">Try a different search or category</p>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-3">
            {filteredItems.map(item => (
              <div
                key={item.id}
                onClick={() => handleAddFurniture(item)}
                className="bg-white border border-neutral-200 rounded-lg p-3 cursor-pointer hover:bg-neutral-50 hover:border-primary-300 hover:shadow-md transition-all duration-200"
              >
                <div className="text-2xl text-center mb-2">
                  {item.thumbnail}
                </div>
                <div className="text-xs font-medium text-center text-neutral-700 mb-1">
                  {item.name}
                </div>
                <div className="text-xs text-center text-neutral-500 mb-1">
                  {item.dimensions.width}×{item.dimensions.depth}×{item.dimensions.height}m
                </div>
                <div className="text-xs text-center text-neutral-400">
                  {item.defaultMaterial}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default ExpandedFurnitureLibrary;
